### ISSUE TITLE
IPv4 not assigned

### ISSUE THREAD

**Issue by dejlek** [ganto/copr-lxd#13]
First, thanks for wonderful project.

I have a tiny problem - my containers do not have IPv4 addresses assigned. Could you please write a guide how to make it work?

**Comment by ganto** [comment]
Unfortunately you didn't give a lot of details what steps you followed to setup LXD. I guess you missed to run the initial setup with `lxd init`. There you should select to create a network bridge `lxdbr0` which also create a DHCP server for you containers.

There are already a lot of guides available how to properly setup LXD. You may want to start with the one on the official website at [linuxcontainers.org: Getting Started](https://linuxcontainers.org/lxd/getting-started-cli/). If you need more information about networking in LXD specifically, you might want to have a look at [stgraber.org: Network Management with LXD](https://stgraber.org/2016/10/27/network-management-with-lxd-2-3/) which is written by one of the LXD core developers.

**Comment by dejlek** [comment]
Thanks for replying - yep I did run it, and I see the lxdbr0 in the list of bridges.

````
lxdbr0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.4.1  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::b0f2:50ff:fee2:e6  prefixlen 64  scopeid 0x20<link>
        ether fe:4a:61:3f:4f:a4  txqueuelen 1000  (Ethernet)
        RX packets 6  bytes 432 (432.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 26  bytes 3290 (3.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0



+------+---------+------+------+------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+------+------+------------+-----------+
| f28  | RUNNING |      |      | PERSISTENT |           |
+------+---------+------+------+------------+-----------+

````
I did uninstall everything and repeated the process few times hoping it will work...

**Comment by ganto** [comment]
What's the output of `lxc network show lxdbr0`? Should be something like:
```
# lxc network show lxdbr0
config:
  dns.domain: lxd.example.com
  ipv4.address: 10.26.230.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:9237:8d06:c9fd::1/64
  ipv6.nat: "true"
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/containers/fc27
managed: true
status: Created
locations:
- none
```
If the `managed` flag is false here, the bridge is not managed by LXD, so the DHCP server might be missing.

And what's the output of `lxc profile show default`? There must be a section:
```
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
```
This means that each container will get a network adapter `eth0` connected to the `lxdbr0` bridge.

**Comment by dejlek** [comment]
````
  dejan@turing$ lxc network show lxdbr0
config:
  ipv4.address: 192.168.4.1/24
  ipv4.nat: "true"
description: ""
name: lxdbr0
type: bridge
used_by:
- /1.0/containers/f28
managed: true
status: Created
locations:
- none

  dejan@turing$ lxc profile show default
config: {}
description: Default LXD profile
devices:
  enp3s0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/f28
````
Weird thing is that it shows eth0... There is no eth0 on this workstation
